# Makefile.nmake pour capture DBD

# Fichier source
SRC = src\features\game_detection\dll\takeGameScreenshot.cpp

# Objet
OBJ = src\features\game_detection\dll\takeGameScreenshot.obj

# DLL à générer
DLL_OUT = capture_dbd.dll

# Règle par défaut
all: $(DLL_OUT)

# Compilation de l'objet
$(OBJ): $(SRC)
	cl.exe /std:c++20 /EHsc /c $(SRC) /Fo$(OBJ) \
	/I"C:\Program Files (x86)\Windows Kits\10\Include\10.0.26100.0\shared" \
	/I"C:\Program Files (x86)\Windows Kits\10\Include\10.0.26100.0\um"

# Création de la DLL
$(DLL_OUT): $(OBJ)
	cl.exe /LD $(OBJ) /link \
	/LIBPATH:"C:\Program Files (x86)\Windows Kits\10\Lib\10.0.26100.0\um\x64" \
	d3d11.lib dxgi.lib user32.lib gdi32.lib /OUT:$(DLL_OUT)

# Nettoyage
fclean:
	del /Q $(OBJ) $(DLL_OUT)

clean:
    del /Q $(OBJ)
