//
// Created by nicolas on 9/15/25.
//

#include "../include/surv_db.h"

perks_t SURV_PERKS_LIST[NB_SURV_PERK] = {
    {SURV_ALL, "Dark Sense", "Sentiment Obscur","assets/icons/perks/survivors/IconPerks_darkSense.png", NULL},
    {SURV_ALL, "Déjà Vu", "Déjà-Vu","assets/icons/perks/survivors/IconPerks_dejaVu.png", NULL},
    {SURV_ALL, "Hope", "Espoir","assets/icons/perks/survivors/IconPerks_hope.png", NULL},
    {SURV_ALL, "Kindred", "Parenté","assets/icons/perks/survivors/IconPerks_kindred.png", NULL},
    {SURV_ALL, "Lightweight", "Poids Plume","assets/icons/perks/survivors/IconPerks_lightweight.png", NULL},
    {SURV_ALL, "No One Left Behind", "On n'Abandonne Personne","assets/icons/perks/survivors/IconPerks_noOneLeftBehind.png", NULL},
    {SURV_ALL, "Plunderer's Instinct", "Instinct de Pillard","assets/icons/perks/survivors/IconPerks_plunderersInstinct.png", NULL},
    {SURV_ALL, "Premonition", "Prémonition","assets/icons/perks/survivors/IconPerks_premonition.png", NULL},
    {SURV_ALL, "Resilience", "Résistance","assets/icons/perks/survivors/IconPerks_resilience.png", NULL},
    {SURV_ALL, "Slippery Meat", "Viande Glissante","assets/icons/perks/survivors/IconPerks_slipperyMeat.png", NULL},
    {SURV_ALL, "Small Game", "Petit Gibier","assets/icons/perks/survivors/IconPerks_smallGame.png", NULL},
    {SURV_ALL, "Spine Chill", "Frisson","assets/icons/perks/survivors/IconPerks_spineChill.png", NULL},
    {SURV_ALL, "This is not Happening", "Ce n'est pas en Train d'Arriver","assets/icons/perks/survivors/IconPerks_thisIsNotHappening.png", NULL},
    {SURV_ALL, "We'll Make It", "Nous Y Arriverons","assets/icons/perks/survivors/IconPerks_wellMakeIt.png", NULL},
    {DWIGHT, "Bond", "Lien", "assets/icons/perks/survivors/IconPerks_bond.png", NULL},
    {DWIGHT, "Leader", "Meneur", "assets/icons/perks/survivors/IconPerks_leader.png", NULL},
    {DWIGHT, "Prove Thyself", "Fais tes Preuves", "assets/icons/perks/survivors/IconPerks_proveThyself.png", NULL},
    {MEG, "Adrenaline", "Adrénaline", "assets/icons/perks/survivors/IconPerks_adrenaline.png", NULL},
    {MEG, "Quick & Quiet", "Rapide et Silencieux", "assets/icons/perks/survivors/IconPerks_quickAndQuiet.png", NULL},
    {MEG, "Sprint Burst", "Course Effrénée", "assets/icons/perks/survivors/IconPerks_sprintBurst.png", NULL},
    {CLAUDETTE, "Botany Knowledge", "Connaissance en Botanique", "assets/icons/perks/survivors/IconPerks_botanyKnowledge.png", NULL},
    {CLAUDETTE, "Empathy", "Empathie", "assets/icons/perks/survivors/IconPerks_empathy.png", NULL},
    {CLAUDETTE, "Self-Care", "Auto-Traitement", "assets/icons/perks/survivors/IconPerks_self-Care.png", NULL},
    {JAKE, "Calm Spirit", "Esprit Calme", "assets/icons/perks/survivors/IconPerks_calmSpirit.png", NULL},
    {JAKE, "Iron Will", "Volonté de Fer", "assets/icons/perks/survivors/IconPerks_ironWill.png", NULL},
    {JAKE, "Saboteur", "Saboteur", "assets/icons/perks/survivors/IconPerks_saboteur.png", NULL},
    {NEA, "Balanced Landing", "Atterrissage Équilibré", "assets/icons/perks/survivors/IconPerks_balancedLanding.png", NULL},
    {NEA, "Streetwise", "Débrouillardise", "assets/icons/perks/survivors/IconPerks_streetwise.png", NULL},
    {NEA, "Urban Evasion", "Évasion Urbaine", "assets/icons/perks/survivors/IconPerks_urbanEvasion.png", NULL},
    {LAURIE, "Decisive Strike", "Coup Décisif", "assets/icons/perks/survivors/IconPerks_decisiveStrike.png", NULL},
    {LAURIE, "Object of Obsession", "Objet d'Obsession", "assets/icons/perks/survivors/IconPerks_objectOfObsession.png", NULL},
    {LAURIE, "Sole Survivor", "Unique Survivant", "assets/icons/perks/survivors/IconPerks_soleSurvivor.png", NULL},
    {ACE, "Ace in the hole", "Atout dans la Manche", "assets/icons/perks/survivors/IconPerks_aceInTheHole.png", NULL},
    {ACE, "Open-Handed", "Le Coeur sur la Main", "assets/icons/perks/survivors/IconPerks_open-Handed.png", NULL},
    {ACE, "Up the Ante", "Augmenter la Mise", "assets/icons/perks/survivors/IconPerks_upTheAnte.png", NULL},
    {BILL, "Borrowed Time", "Surcis","assets/icons/perks/survivors/IconPerks_borrowedTime.png", NULL},
    {BILL, "Left Behind", "Abandonné","assets/icons/perks/survivors/IconPerks_leftBehind.png", NULL},
    {BILL, "Unbreakable", "Indéfectible","assets/icons/perks/survivors/IconPerks_unbreakable.png", NULL},
    {FENG, "Alert", "Vigilant","assets/icons/perks/survivors/IconPerks_alert.png", NULL},
    {FENG, "Lithe", "Souple","assets/icons/perks/survivors/IconPerks_lithe.png", NULL},
    {FENG, "Technician", "Technicien","assets/icons/perks/survivors/IconPerks_technician.png", NULL},
    {DAVID, "Dead Hard", "Dur à Cuire","assets/icons/perks/survivors/IconPerks_deadHard.png", NULL},
    {DAVID, "No Mither", "Même pas Mal","assets/icons/perks/survivors/IconPerks_noMither.png", NULL},
    {DAVID, "We're Gonna Live Forever", "Nous Vivrons Éternellement","assets/icons/perks/survivors/IconPerks_wereGonnaLiveForever.png", NULL},
    {QUENTIN, "Pharmacy", "Pharmacie","assets/icons/perks/survivors/IconPerks_pharmacy.png", NULL},
    {QUENTIN, "Vigil", "Veillée","assets/icons/perks/survivors/IconPerks_vigil.png", NULL},
    {QUENTIN, "Wake Up!", "Debout!","assets/icons/perks/survivors/IconPerks_wakeUp.png", NULL},
    {TAPP, "Detective's Hunch", "Intuition de l'Inspecteur","assets/icons/perks/survivors/IconPerks_detectivesHunch.png", NULL},
    {TAPP, "Stake Out", "En Planque","assets/icons/perks/survivors/IconPerks_stakeOut.png", NULL},
    {TAPP, "Tenacity", "Tenacité","assets/icons/perks/survivors/IconPerks_tenacity.png", NULL},
    {KATE, "Boil Over", "Effusion","assets/icons/perks/survivors/IconPerks_boilOver.png", NULL},
    {KATE, "Dance With Me", "Danse Avec Moi","assets/icons/perks/survivors/IconPerks_danceWithMe.png", NULL},
    {KATE, "Windows of Opportunity", "Parfaite Occasion","assets/icons/perks/survivors/IconPerks_windowsOfOpportunity.png", NULL},
    {ADAM, "Autodidact", "Autididacte","assets/icons/perks/survivors/IconPerks_autodidact.png", NULL},
    {ADAM, "Deliverance", "Libération","assets/icons/perks/survivors/IconPerks_deliverance.png", NULL},
    {ADAM, "Diversion", "Diversion","assets/icons/perks/survivors/IconPerks_diversion.png", NULL},
    {JEFF, "Aftercare", "Suivi des Soins","assets/icons/perks/survivors/IconPerks_aftercare.png", NULL},
    {JEFF, "Breakdown", "Effondrement","assets/icons/perks/survivors/IconPerks_breakdown.png", NULL},
    {JEFF, "Distortion", "Distorsion","assets/icons/perks/survivors/IconPerks_distortion.png", NULL},
    {JANE, "Head On", "De Front","assets/icons/perks/survivors/IconPerks_headOn.png", NULL},
    {JANE, "Poised", "Assurance","assets/icons/perks/survivors/IconPerks_poised.png", NULL},
    {JANE, "Solidarity", "Solidarité","assets/icons/perks/survivors/IconPerks_solidarity.png", NULL},
    {ASH, "Buckle Up", "Accrochez-Vous","assets/icons/perks/survivors/IconPerks_buckleUp.png", NULL},
    {ASH, "Flip-Flop", "À la Revoyure","assets/icons/perks/survivors/IconPerks_flip-Flop.png", NULL},
    {ASH, "Mettle of Man", "Force de Caractère","assets/icons/perks/survivors/IconPerks_mettleOfMan.png", NULL},
    {NANCY, "Better Together", "Mieux Ensemble","assets/icons/perks/survivors/IconPerks_betterTogether.png", NULL},
    {NANCY, "Fixated", "Obnubilé","assets/icons/perks/survivors/IconPerks_fixated.png", NULL},
    {NANCY, "Inner Strength", "Force Intérieur","assets/icons/perks/survivors/IconPerks_innerStrength.png", NULL},
    {STEVE, "Babysitter", "Baby-Sitter","assets/icons/perks/survivors/IconPerks_babysitter.png", NULL},
    {STEVE, "Camaraderie", "Camaraderie","assets/icons/perks/survivors/IconPerks_camaraderie.png", NULL},
    {STEVE, "Second Wind", "Second Souffle","assets/icons/perks/survivors/IconPerks_secondWind.png", NULL},
    {YUI, "Any Means Necessary", "Par Tous les Moyens","assets/icons/perks/survivors/IconPerks_anyMeansNecessary.png", NULL},
    {YUI, "Breakout", "Évasion","assets/icons/perks/survivors/IconPerks_breakout.png", NULL},
    {YUI, "Lucky Break", "Coup de Chance","assets/icons/perks/survivors/IconPerks_luckyBreak.png", NULL},
    {ZARINA, "For the People", "Pour le Peuple","assets/icons/perks/survivors/IconPerks_forThePeople.png", NULL},
    {ZARINA, "Off the Record", "Confidentiel","assets/icons/perks/survivors/IconPerks_offTheRecord.png", NULL},
    {ZARINA, "Red Herring", "Leurre","assets/icons/perks/survivors/IconPerks_redHerring.png", NULL},
    {CHERYL, "Blood Pact", "Pacte de Sang","assets/icons/perks/survivors/IconPerks_bloodPact.png", NULL},
    {CHERYL, "Repressed Alliance", "Alliance Refoulée","assets/icons/perks/survivors/IconPerks_repressedAlliance.png", NULL},
    {CHERYL, "Soul Guard", "Protection de l'Âme","assets/icons/perks/survivors/IconPerks_soulGuard.png", NULL},
    {FELIX, "Built to Last", "Conçu pour Durer","assets/icons/perks/survivors/IconPerks_builtToLast.png", NULL},
    {FELIX, "Desperate Measures", "Mesures Désespérées","assets/icons/perks/survivors/IconPerks_desperateMeasures.png", NULL},
    {FELIX, "Visionary", "Visionnaire","assets/icons/perks/survivors/IconPerks_visionary.png", NULL},
    {ELODIE, "Appraisal", "Estimation","assets/icons/perks/survivors/IconPerks_appraisal.png", NULL},
    {ELODIE, "Deception", "Supercherie","assets/icons/perks/survivors/IconPerks_deception.png", NULL},
    {ELODIE, "Power Struggle", "Bras de Fer","assets/icons/perks/survivors/IconPerks_powerStruggle.png", NULL},
    {YUN_JIN, "Fast Track", "Voie Rapide","assets/icons/perks/survivors/IconPerks_fastTrack.png", NULL},
    {YUN_JIN, "Self-Preservation", "Instinct de Survie","assets/icons/perks/survivors/IconPerks_self-Preservation.png", NULL},
    {YUN_JIN, "Smash Hit", "Succès Écrasant","assets/icons/perks/survivors/IconPerks_smashHit.png", NULL},
    {JILL, "Blast Mine", "Mine Explosive","assets/icons/perks/survivors/IconPerks_blastMine.png", NULL},
    {JILL, "Counterforce", "Contre-Force","assets/icons/perks/survivors/IconPerks_counterforce.png", NULL},
    {JILL, "Resurgence", "Renaissance","assets/icons/perks/survivors/IconPerks_resurgence.png", NULL},
    {LEON, "Bite the Bullet", "Serrer les Dents","assets/icons/perks/survivors/IconPerks_biteTheBullet.png", NULL},
    {LEON, "Flashbang", "Grenade Aveuglante","assets/icons/perks/survivors/IconPerks_flashbang.png", NULL},
    {LEON, "Rookie Spirit", "Détermination du Bleu","assets/icons/perks/survivors/IconPerks_rookieSpirit.png", NULL},
    {MIKAELA, "Boon: Circle of Healing", "Bénédiction: Cercle de Soins","assets/icons/perks/survivors/IconPerks_boonCircleOfHealing.png", NULL},
    {MIKAELA, "Boon: Shadow Step", "Bénédiction: Marche de l'Ombre","assets/icons/perks/survivors/IconPerks_boonShadowStep.png", NULL},
    {MIKAELA, "Clairvoyance", "Clairvoyance","assets/icons/perks/survivors/IconPerks_clairvoyance.png", NULL},
    {JONAH, "Boon: Exponential", "Bénédiction: Exponentiel","assets/icons/perks/survivors/IconPerks_boonExponential.png", NULL},
    {JONAH, "Corrective Action", "Mesure de Correction","assets/icons/perks/survivors/IconPerks_correctiveAction.png", NULL},
    {JONAH, "Overcome", "Surmonter","assets/icons/perks/survivors/IconPerks_overcome.png", NULL},
    {YOICHI, "Boon: Dark Theory", "Bénédiction: Théorie Ténébreuse","assets/icons/perks/survivors/IconPerks_boonDarkTheory.png", NULL},
    {YOICHI, "Empathic Connection", "Connexion Empathique","assets/icons/perks/survivors/IconPerks_empathicConnection.png", NULL},
    {YOICHI, "Parental Guidance", "Conseils Parentaux","assets/icons/perks/survivors/IconPerks_parentalGuidance.png", NULL},
    {HADDIE, "Inner Focus", "Concentration Intérieure","assets/icons/perks/survivors/IconPerks_innerFocus.png", NULL},
    {HADDIE, "Overzealous", "Excès de Zèle","assets/icons/perks/survivors/IconPerks_overzealous.png", NULL},
    {HADDIE, "Residual Manifest", "Manifeste Résiduel","assets/icons/perks/survivors/IconPerks_residualManifest.png", NULL},
    {ADA, "Low Profile", "Profil Bas","assets/icons/perks/survivors/IconPerks_lowProfile.png", NULL},
    {ADA, "Reactive Healing", "Guérison Réactive","assets/icons/perks/survivors/IconPerks_reactiveHealing.png", NULL},
    {ADA, "Wiretap", "Micro Caché","assets/icons/perks/survivors/IconPerks_wiretap.png", NULL},
    {REBECCA, "Better than New", "Mieux que Neuf","assets/icons/perks/survivors/IconPerks_betterThanNew.png", NULL},
    {REBECCA, "Hyperfocus", "Hyperconcentration","assets/icons/perks/survivors/IconPerks_hyperfocus.png", NULL},
    {REBECCA, "Reassurance", "Réconfort","assets/icons/perks/survivors/IconPerks_reassurance.png", NULL},
    {VITTORIO, "Fogwise", "Débrouillard","assets/icons/perks/survivors/IconPerks_fogwise.png", NULL},
    {VITTORIO, "Potential Energy", "Énergie Potentielle","assets/icons/perks/survivors/IconPerks_potentialEnergy.png", NULL},
    {VITTORIO, "Quick Gambit", "Gambit Prompt","assets/icons/perks/survivors/IconPerks_quickGambit.png", NULL},
    {THALITA, "Cut Loose", "Hors de Contrôle","assets/icons/perks/survivors/IconPerks_cutLoose.png", NULL},
    {THALITA, "Friendly Competition", "Compétition Amicale","assets/icons/perks/survivors/IconPerks_friendlyCompetition.png", NULL},
    {THALITA, "Teamwork: Power of Two", "Travail d'Équipe: Pouvoir des Deux","assets/icons/perks/survivors/IconPerks_teamworkPowerOfTwo.png", NULL},
    {RENATO, "Background Player", "Joueur Arrière","assets/icons/perks/survivors/IconPerks_backgroundPlayer.png", NULL},
    {RENATO, "Blood Rush", "Coup de Collier","assets/icons/perks/survivors/IconPerks_bloodRush.png", NULL},
    {RENATO, "Teamwork: Collective Stealth", "Travail d'Équipe: Discrétion Collective","assets/icons/perks/survivors/IconPerks_teamworkCollectiveStealth.png", NULL},
    {GABRIEL, "Made for This", "Fait Pour Ça","assets/icons/perks/survivors/IconPerks_madeForThis.png", NULL},
    {GABRIEL, "Scavenger", "Récupérateur","assets/icons/perks/survivors/IconPerks_scavenger.png", NULL},
    {GABRIEL, "Troubleshooter", "Expert","assets/icons/perks/survivors/IconPerks_troubleshooter.png", NULL},
    {NICOLAS, "Dramaturgy", "Dramaturgie","assets/icons/perks/survivors/IconPerks_dramaturgy.png", NULL},
    {NICOLAS, "Plot Twist", "Rebondissement","assets/icons/perks/survivors/IconPerks_plotTwist.png", NULL},
    {NICOLAS, "Scene Partner", "Partenaire de Scène","assets/icons/perks/survivors/IconPerks_scenePartner.png", NULL},
    {ELLEN, "Chemical Trap", "Piège Chimique","assets/icons/perks/survivors/IconPerks_chemicalTrap.png", NULL},
    {ELLEN, "Light-Footed", "À Pas de Chat","assets/icons/perks/survivors/IconPerks_light-Footed.png", NULL},
    {ELLEN, "Lucky Star", "Bonne Étoile","assets/icons/perks/survivors/IconPerks_luckyStar.png", NULL},
    {ALAN, "Boon: Illumination", "Bénédiction: Illumination","assets/icons/perks/survivors/IconPerks_boonIllumination.png", NULL},
    {ALAN, "Champion of Light", "Champion de la Lumière","assets/icons/perks/survivors/IconPerks_championOfLight.png", NULL},
    {ALAN, "Deadline", "Échéance","assets/icons/perks/survivors/IconPerks_deadline.png", NULL},
    {SABLE, "Invocation: Weaving Spiders", "Invocation: Araignées Tisseuses","assets/icons/perks/survivors/IconPerks_invocationWeavingSpiders.png", NULL},
    {SABLE, "Strength in Shadows", "L'Ombre Fait la Force","assets/icons/perks/survivors/IconPerks_strengthInShadows.png", NULL},
    {SABLE, "Wicked", "Malice","assets/icons/perks/survivors/IconPerks_wicked.png", NULL},
    {AESTRI, "Bardic Inspiration", "Inspiration Bardique","assets/icons/perks/survivors/IconPerks_bardicInspiration.png", NULL},
    {AESTRI, "Mirrored Illusion", "Illusion du Miroir","assets/icons/perks/survivors/IconPerks_mirroredIllusion.png", NULL},
    {AESTRI, "Still Sight", "Vision Immobile","assets/icons/perks/survivors/IconPerks_stillSight.png", NULL},
    {LARA, "Finesse", "Finesse","assets/icons/perks/survivors/IconPerks_finesse.png", NULL},
    {LARA, "Hardened", "Endurcie","assets/icons/perks/survivors/IconPerks_hardened.png", NULL},
    {LARA, "Specialist", "Spécialiste","assets/icons/perks/survivors/IconPerks_specialist.png", NULL},
    {TREVOR, "Exultation", "Exultation","assets/icons/perks/survivors/IconPerks_Exultation.png", NULL},
    {TREVOR, "Eyes of Belmont", "Yeux de Belmont","assets/icons/perks/survivors/IconPerks_EyesOfBelmont.png", NULL},
    {TREVOR, "Moment of Glory", "Moment de Gloire","assets/icons/perks/survivors/IconPerks_MomentOfGlory.png", NULL},
    {TAURIE, "Clean Break", "Rupture Nette","assets/icons/perks/survivors/IconPerks_cleanBreak.png", NULL},
    {TAURIE, "Invocation: Treacherous Crows", "Invocation: Corbeaux Traîtres","assets/icons/perks/survivors/IconPerks_invocationTreacherousCrows.png", NULL},
    {TAURIE, "Shoulder the Burden", "Endosse le Fardeau","assets/icons/perks/survivors/IconPerks_shoulderTheBurden.png", NULL},
};
