//
// Created by nicolas on 9/15/25.
//

#include "../include/surv_db.h"

surv_perks_t SURV_PERKS_LIST[NB_SURV_PERK] = {
    {SURV_ALL, "Dark Sense", "Sentiment Obscur","assets/icons/perks/survivors/IconPerks_darkSense.png"},
    {SURV_ALL, "Déjà Vu", "Déjà-Vu","assets/icons/perks/survivors/IconPerks_dejaVu.png"},
    {SURV_ALL, "Hope", "Espoir","assets/icons/perks/survivors/IconPerks_hope.png"},
    {SURV_ALL, "Kindred", "Parenté","assets/icons/perks/survivors/IconPerks_kindred.png"},
    {SURV_ALL, "Lightweight", "Poids Plume","assets/icons/perks/survivors/IconPerks_lightweight.png"},
    {SURV_ALL, "No One Left Behind", "On n'Abandonne Personne","assets/icons/perks/survivors/IconPerks_noOneLeftBehind.png"},
    {SURV_ALL, "Plunderer's Instinct", "Instinct de Pillard","assets/icons/perks/survivors/IconPerks_plunderersInstinct.png"},
    {SURV_ALL, "Premonition", "Prémonition","assets/icons/perks/survivors/IconPerks_premonition.png"},
    {SURV_ALL, "Resilience", "Résistance","assets/icons/perks/survivors/IconPerks_resilience.png"},
    {SURV_ALL, "Slippery Meat", "Viande Glissante","assets/icons/perks/survivors/IconPerks_slipperyMeat.png"},
    {SURV_ALL, "Small Game", "Petit Gibier","assets/icons/perks/survivors/IconPerks_smallGame.png"},
    {SURV_ALL, "Spine Chill", "Frisson","assets/icons/perks/survivors/IconPerks_spineChill.png"},
    {SURV_ALL, "This is not Happening", "Ce n'est pas en Train d'Arriver","assets/icons/perks/survivors/IconPerks_thisIsNotHappening.png"},
    {SURV_ALL, "We'll Make It", "Nous Y Arriverons","assets/icons/perks/survivors/IconPerks_wellMakeIt.png"},
    {DWIGHT, "Bond", "Lien", "assets/icons/perks/survivors/IconPerks_bond.png"},
    {DWIGHT, "Leader", "Meneur", "assets/icons/perks/survivors/IconPerks_leader.png"},
    {DWIGHT, "Prove Thyself", "Fais tes Preuves", "assets/icons/perks/survivors/IconPerks_proveThyself.png"},
    {MEG, "Adrenaline", "Adrénaline", "assets/icons/perks/survivors/IconPerks_adrenaline.png"},
    {MEG, "Quick & Quiet", "Rapide et Silencieux", "assets/icons/perks/survivors/IconPerks_quickAndQuiet.png"},
    {MEG, "Sprint Burst", "Course Effrénée", "assets/icons/perks/survivors/IconPerks_sprintBurst.png"},
    {CLAUDETTE, "Botany Knowledge", "Connaissance en Botanique", "assets/icons/perks/survivors/IconPerks_botanyKnowledge.png"},
    {CLAUDETTE, "Empathy", "Empathie", "assets/icons/perks/survivors/IconPerks_empathy.png"},
    {CLAUDETTE, "Self-Care", "Auto-Traitement", "assets/icons/perks/survivors/IconPerks_self-Care.png"},
    {JAKE, "Calm Spirit", "Esprit Calme", "assets/icons/perks/survivors/IconPerks_calmSpirit.png"},
    {JAKE, "Iron Will", "Volonté de Fer", "assets/icons/perks/survivors/IconPerks_ironWill.png"},
    {JAKE, "Saboteur", "Saboteur", "assets/icons/perks/survivors/IconPerks_saboteur.png"},
    {NEA, "Balanced Landing", "Atterrissage Équilibré", "assets/icons/perks/survivors/IconPerks_balancedLanding.png"},
    {NEA, "Streetwise", "Débrouillardise", "assets/icons/perks/survivors/IconPerks_streetwise.png"},
    {NEA, "Urban Evasion", "Évasion Urbaine", "assets/icons/perks/survivors/IconPerks_urbanEvasion.png"},
    {LAURIE, "Decisive Strike", "Coup Décisif", "assets/icons/perks/survivors/IconPerks_decisiveStrike.png"},
    {LAURIE, "Object of Obsession", "Objet d'Obsession", "assets/icons/perks/survivors/IconPerks_objectOfObsession.png"},
    {LAURIE, "Sole Survivor", "Unique Survivant", "assets/icons/perks/survivors/IconPerks_soleSurvivor.png"},
    {ACE, "Ace in the hole", "Atout dans la Manche", "assets/icons/perks/survivors/IconPerks_aceInTheHole.png"},
    {ACE, "Open-Handed", "Le Coeur sur la Main", "assets/icons/perks/survivors/IconPerks_open-Handed.png"},
    {ACE, "Up the Ante", "Augmenter la Mise", "assets/icons/perks/survivors/IconPerks_upTheAnte.png"},
    {BILL, "Borrowed Time", "Surcis","assets/icons/perks/survivors/IconPerks_borrowedTime.png"},
    {BILL, "Left Behind", "Abandonné","assets/icons/perks/survivors/IconPerks_leftBehind.png"},
    {BILL, "Unbreakable", "Indéfectible","assets/icons/perks/survivors/IconPerks_unbreakable.png"},
    {FENG, "Alert", "Vigilant","assets/icons/perks/survivors/IconPerks_alert.png"},
    {FENG, "Lithe", "Souple","assets/icons/perks/survivors/IconPerks_lithe.png"},
    {FENG, "Technician", "Technicien","assets/icons/perks/survivors/IconPerks_technician.png"},
    {DAVID, "Dead Hard", "Dur à Cuire","assets/icons/perks/survivors/IconPerks_deadHard.png"},
    {DAVID, "No Mither", "Même pas Mal","assets/icons/perks/survivors/IconPerks_noMither.png"},
    {DAVID, "We're Gonna Live Forever", "Nous Vivrons Éternellement","assets/icons/perks/survivors/IconPerks_wereGonnaLiveForever.png"},
    {QUENTIN, "Pharmacy", "Pharmacie","assets/icons/perks/survivors/IconPerks_pharmacy.png"},
    {QUENTIN, "Vigil", "Veillée","assets/icons/perks/survivors/IconPerks_vigil.png"},
    {QUENTIN, "Wake Up!", "Debout!","assets/icons/perks/survivors/IconPerks_wakeUp.png"},
    {TAPP, "Detective's Hunch", "Intuition de l'Inspecteur","assets/icons/perks/survivors/IconPerks_detectivesHunch.png"},
    {TAPP, "Stake Out", "En Planque","assets/icons/perks/survivors/IconPerks_stakeOut.png"},
    {TAPP, "Tenacity", "Tenacité","assets/icons/perks/survivors/IconPerks_tenacity.png"},
    {KATE, "Boil Over", "Effusion","assets/icons/perks/survivors/IconPerks_boilOver.png"},
    {KATE, "Dance With Me", "Danse Avec Moi","assets/icons/perks/survivors/IconPerks_danceWithMe.png"},
    {KATE, "Windows of Opportunity", "Parfaite Occasion","assets/icons/perks/survivors/IconPerks_windowsOfOpportunity.png"},
    {ADAM, "Autodidact", "Autididacte","assets/icons/perks/survivors/IconPerks_autodidact.png"},
    {ADAM, "Deliverance", "Libération","assets/icons/perks/survivors/IconPerks_deliverance.png"},
    {ADAM, "Diversion", "Diversion","assets/icons/perks/survivors/IconPerks_diversion.png"},
    {JEFF, "Aftercare", "Suivi des Soins","assets/icons/perks/survivors/IconPerks_aftercare.png"},
    {JEFF, "Breakdown", "Effondrement","assets/icons/perks/survivors/IconPerks_breakdown.png"},
    {JEFF, "Distortion", "Distorsion","assets/icons/perks/survivors/IconPerks_distortion.png"},
    {JANE, "Head On", "De Front","assets/icons/perks/survivors/IconPerks_headOn.png"},
    {JANE, "Poised", "Assurance","assets/icons/perks/survivors/IconPerks_poised.png"},
    {JANE, "Solidarity", "Solidarité","assets/icons/perks/survivors/IconPerks_solidarity.png"},
    {ASH, "Buckle Up", "Accrochez-Vous","assets/icons/perks/survivors/IconPerks_buckleUp.png"},
    {ASH, "Flip-Flop", "À la Revoyure","assets/icons/perks/survivors/IconPerks_flip-Flop.png"},
    {ASH, "Mettle of Man", "Force de Caractère","assets/icons/perks/survivors/IconPerks_mettleOfMan.png"},
    {NANCY, "Better Together", "Mieux Ensemble","assets/icons/perks/survivors/IconPerks_betterTogether.png"},
    {NANCY, "Fixated", "Obnubilé","assets/icons/perks/survivors/IconPerks_fixated.png"},
    {NANCY, "Inner Strength", "Force Intérieur","assets/icons/perks/survivors/IconPerks_innerStrength.png"},
    {STEVE, "Babysitter", "Baby-Sitter","assets/icons/perks/survivors/IconPerks_babysitter.png"},
    {STEVE, "Camaraderie", "Camaraderie","assets/icons/perks/survivors/IconPerks_camaraderie.png"},
    {STEVE, "Second Wind", "Second Souffle","assets/icons/perks/survivors/IconPerks_secondWind.png"},
    {YUI, "Any Means Necessary", "Par Tous les Moyens","assets/icons/perks/survivors/IconPerks_anyMeansNecessary.png"},
    {YUI, "Breakout", "Évasion","assets/icons/perks/survivors/IconPerks_breakout.png"},
    {YUI, "Lucky Break", "Coup de Chance","assets/icons/perks/survivors/IconPerks_luckyBreak.png"},
    {ZARINA, "For the People", "Pour le Peuple","assets/icons/perks/survivors/IconPerks_forThePeople.png"},
    {ZARINA, "Off the Record", "Confidentiel","assets/icons/perks/survivors/IconPerks_offTheRecord.png"},
    {ZARINA, "Red Herring", "Leurre","assets/icons/perks/survivors/IconPerks_redHerring.png"},
    {CHERYL, "Blood Pact", "Pacte de Sang","assets/icons/perks/survivors/IconPerks_bloodPact.png"},
    {CHERYL, "Repressed Alliance", "Alliance Refoulée","assets/icons/perks/survivors/IconPerks_repressedAlliance.png"},
    {CHERYL, "Soul Guard", "Protection de l'Âme","assets/icons/perks/survivors/IconPerks_soulGuard.png"},
    {FELIX, "Built to Last", "Conçu pour Durer","assets/icons/perks/survivors/IconPerks_builtToLast.png"},
    {FELIX, "Desperate Measures", "Mesures Désespérées","assets/icons/perks/survivors/IconPerks_desperateMeasures.png"},
    {FELIX, "Visionary", "Visionnaire","assets/icons/perks/survivors/IconPerks_visionary.png"},
    {ELODIE, "Appraisal", "Estimation","assets/icons/perks/survivors/IconPerks_appraisal.png"},
    {ELODIE, "Deception", "Supercherie","assets/icons/perks/survivors/IconPerks_deception.png"},
    {ELODIE, "Power Struggle", "Bras de Fer","assets/icons/perks/survivors/IconPerks_powerStruggle.png"},
    {YUN_JIN, "Fast Track", "Voie Rapide","assets/icons/perks/survivors/IconPerks_fastTrack.png"},
    {YUN_JIN, "Self-Preservation", "Instinct de Survie","assets/icons/perks/survivors/IconPerks_self-Preservation.png"},
    {YUN_JIN, "Smash Hit", "Succès Écrasant","assets/icons/perks/survivors/IconPerks_smashHit.png"},
    {JILL, "Blast Mine", "Mine Explosive","assets/icons/perks/survivors/IconPerks_blastMine.png"},
    {JILL, "Counterforce", "Contre-Force","assets/icons/perks/survivors/IconPerks_counterforce.png"},
    {JILL, "Resurgence", "Renaissance","assets/icons/perks/survivors/IconPerks_resurgence.png"},
    {LEON, "Bite the Bullet", "Serrer les Dents","assets/icons/perks/survivors/IconPerks_biteTheBullet.png"},
    {LEON, "Flashbang", "Grenade Aveuglante","assets/icons/perks/survivors/IconPerks_flashbang.png"},
    {LEON, "Rookie Spirit", "Détermination du Bleu","assets/icons/perks/survivors/IconPerks_rookieSpirit.png"},
    {MIKAELA, "Boon: Circle of Healing", "Bénédiction: Cercle de Soins","assets/icons/perks/survivors/IconPerks_boonCircleOfHealing.png"},
    {MIKAELA, "Boon: Shadow Step", "Bénédiction: Marche de l'Ombre","assets/icons/perks/survivors/IconPerks_boonShadowStep.png"},
    {MIKAELA, "Clairvoyance", "Clairvoyance","assets/icons/perks/survivors/IconPerks_clairvoyance.png"},
    {JONAH, "Boon: Exponential", "Bénédiction: Exponentiel","assets/icons/perks/survivors/IconPerks_boonExponential.png"},
    {JONAH, "Corrective Action", "Mesure de Correction","assets/icons/perks/survivors/IconPerks_correctiveAction.png"},
    {JONAH, "Overcome", "Surmonter","assets/icons/perks/survivors/IconPerks_overcome.png"},
    {YOICHI, "Boon: Dark Theory", "Bénédiction: Théorie Ténébreuse","assets/icons/perks/survivors/IconPerks_boonDarkTheory.png"},
    {YOICHI, "Empathic Connection", "Connexion Empathique","assets/icons/perks/survivors/IconPerks_empathicConnection.png"},
    {YOICHI, "Parental Guidance", "Conseils Parentaux","assets/icons/perks/survivors/IconPerks_parentalGuidance.png"},
    {HADDIE, "Inner Focus", "Concentration Intérieure","assets/icons/perks/survivors/IconPerks_innerFocus.png"},
    {HADDIE, "Overzealous", "Excès de Zèle","assets/icons/perks/survivors/IconPerks_overzealous.png"},
    {HADDIE, "Residual Manifest", "Manifeste Résiduel","assets/icons/perks/survivors/IconPerks_residualManifest.png"},
    {ADA, "Low Profile", "Profil Bas","assets/icons/perks/survivors/IconPerks_lowProfile.png"},
    {ADA, "Reactive Healing", "Guérison Réactive","assets/icons/perks/survivors/IconPerks_reactiveHealing.png"},
    {ADA, "Wiretap", "Micro Caché","assets/icons/perks/survivors/IconPerks_wiretap.png"},
    {REBECCA, "Better than New", "Mieux que Neuf","assets/icons/perks/survivors/IconPerks_betterThanNew.png"},
    {REBECCA, "Hyperfocus", "Hyperconcentration","assets/icons/perks/survivors/IconPerks_hyperfocus.png"},
    {REBECCA, "Reassurance", "Réconfort","assets/icons/perks/survivors/IconPerks_reassurance.png"},
    {VITTORIO, "Fogwise", "Débrouillard","assets/icons/perks/survivors/IconPerks_fogwise.png"},
    {VITTORIO, "Potential Energy", "Énergie Potentielle","assets/icons/perks/survivors/IconPerks_potentialEnergy.png"},
    {VITTORIO, "Quick Gambit", "Gambit Prompt","assets/icons/perks/survivors/IconPerks_quickGambit.png"},
    {THALITA, "Cut Loose", "Hors de Contrôle","assets/icons/perks/survivors/IconPerks_cutLoose.png"},
    {THALITA, "Friendly Competition", "Compétition Amicale","assets/icons/perks/survivors/IconPerks_friendlyCompetition.png"},
    {THALITA, "Teamwork: Power of Two", "Travail d'Équipe: Pouvoir des Deux","assets/icons/perks/survivors/IconPerks_teamworkPowerOfTwo.png"},
    {RENATO, "Background Player", "Joueur Arrière","assets/icons/perks/survivors/IconPerks_backgroundPlayer.png"},
    {RENATO, "Blood Rush", "Coup de Collier","assets/icons/perks/survivors/IconPerks_bloodRush.png"},
    {RENATO, "Teamwork: Collective Stealth", "Travail d'Équipe: Discrétion Collective","assets/icons/perks/survivors/IconPerks_teamworkCollectiveStealth.png"},
    {GABRIEL, "Made for This", "Fait Pour Ça","assets/icons/perks/survivors/IconPerks_madeForThis.png"},
    {GABRIEL, "Scavenger", "Récupérateur","assets/icons/perks/survivors/IconPerks_scavenger.png"},
    {GABRIEL, "Troubleshooter", "Expert","assets/icons/perks/survivors/IconPerks_troubleshooter.png"},
    {NICOLAS, "Dramaturgy", "Dramaturgie","assets/icons/perks/survivors/IconPerks_dramaturgy.png"},
    {NICOLAS, "Plot Twist", "Rebondissement","assets/icons/perks/survivors/IconPerks_plotTwist.png"},
    {NICOLAS, "Scene Partner", "Partenaire de Scène","assets/icons/perks/survivors/IconPerks_scenePartner.png"},
    {ELLEN, "Chemical Trap", "Piège Chimique","assets/icons/perks/survivors/IconPerks_chemicalTrap.png"},
    {ELLEN, "Light-Footed", "À Pas de Chat","assets/icons/perks/survivors/IconPerks_light-Footed.png"},
    {ELLEN, "Lucky Star", "Bonne Étoile","assets/icons/perks/survivors/IconPerks_luckyStar.png"},
    {ALAN, "Boon: Illumination", "Bénédiction: Illumination","assets/icons/perks/survivors/IconPerks_boonIllumination.png"},
    {ALAN, "Champion of Light", "Champion de la Lumière","assets/icons/perks/survivors/IconPerks_championOfLight.png"},
    {ALAN, "Deadline", "Échéance","assets/icons/perks/survivors/IconPerks_deadline.png"},
    {SABLE, "Invocation: Weaving Spiders", "Invocation: Araignées Tisseuses","assets/icons/perks/survivors/IconPerks_invocationWeavingSpiders.png"},
    {SABLE, "Strength in Shadows", "L'Ombre Fait la Force","assets/icons/perks/survivors/IconPerks_strengthInShadows.png"},
    {SABLE, "Wicked", "Malice","assets/icons/perks/survivors/IconPerks_wicked.png"},
    {AESTRI, "Bardic Inspiration", "Inspiration Bardique","assets/icons/perks/survivors/IconPerks_bardicInspiration.png"},
    {AESTRI, "Mirrored Illusion", "Illusion du Miroir","assets/icons/perks/survivors/IconPerks_mirroredIllusion.png"},
    {AESTRI, "Still Sight", "Vision Immobile","assets/icons/perks/survivors/IconPerks_stillSight.png"},
    {LARA, "Finesse", "Finesse","assets/icons/perks/survivors/IconPerks_finesse.png"},
    {LARA, "Hardened", "Endurcie","assets/icons/perks/survivors/IconPerks_hardened.png"},
    {LARA, "Specialist", "Spécialiste","assets/icons/perks/survivors/IconPerks_specialist.png"},
    {TREVOR, "Exultation", "Exultation","assets/icons/perks/survivors/IconPerks_Exultation.png"},
    {TREVOR, "Eyes of Belmont", "Yeux de Belmont","assets/icons/perks/survivors/IconPerks_EyesOfBelmont.png"},
    {TREVOR, "Moment of Glory", "Moment de Gloire","assets/icons/perks/survivors/IconPerks_MomentOfGlory.png"},
    {TAURIE, "Clean Break", "Rupture Nette","assets/icons/perks/survivors/IconPerks_cleanBreak.png"},
    {TAURIE, "Invocation: Treacherous Crows", "Invocation: Corbeaux Traîtres","assets/icons/perks/survivors/IconPerks_invocationTreacherousCrows.png"},
    {TAURIE, "Shoulder the Burden", "Endosse le Fardeau","assets/icons/perks/survivors/IconPerks_shoulderTheBurden.png"},
};